### PR TITLE
Skeleton

### PR DESCRIPTION
**Pull request by sergiogval**
On this PR I got the webpack dependencies in order, created a JS file in order to dynamics creation of the default tasks, created the style and also configurated webpack. I also included some code in order to advance with the second part of the project that is about add and remove entries.

### CODE REVIEW

**Comment by TedLivist** [comment]
Hey @sergiogval, here are the steps on how to configure your styling with webpack

- [ ] First of all, remove the lines I highlighted in the image below from your **`src/index.html`** file. After the correct configuration, webpack bundling will take care of your CSS and JS anyways.

  sergio-css

- [ ] Run the following command as highlighted in the Microverse linked article [here](https://webpack.js.org/guides/asset-management/#loading-css)

  ```
  npm install --save-dev style-loader css-loader
  ```

- [ ] Next, add this setup to your `webpack.config.js` file
  ```
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: ['style-loader', 'css-loader'],
      },
    ],
  },
  ```

- [ ] There seems to be something run with your Javascript code in `src/index.js`. When I bundle and open your app in the browser, the app loads forever. I would suggest you comment out your entire JS code in that file to proceed and see the result.
- [ ] In your `src/index.js` file, import your `main.css` at the top of the file like so:

  ```
  import './main.css';
  ```
- [ ] Finally, run your build command: `npm run build-dev` and open the `dist/index.html` file. Your page styling should match what you are looking for.

**Review by TedLivist — CHANGES_REQUESTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @sergiogval,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### You have submitted a project, that does not have a descriptive README file

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by sergiogval** [comment]
@TedLivist Your suggestions were very useful. I really appreciate them. Since its a lot of bad settled stuff in this repo, I've decided create a new one, taking your advices and do a little `Ctl + C`  `Ctl + v` in order to bring the value code in here. Thanks!

**Comment by TedLivist** [comment]
Alright @sergiogval. Glad to have helped. Happy coding.

**Pull request closed without merging**
